added rated-temperature for led-display project
JITx-Inc/open-components-database pull request #243
Opened 2022-06-24 22:01 UTC by bhusang

Added rated-temperature() to some components to enable erc checks to pass on the led-display project

2022-06-29 21:50 UTC, electricfungi approved these changes

2022-06-29 21:51 UTC, electricfungi requested changes
I think the land pattern only parts need a min max temp range that won't fail for some design values. -40 to 125 is too tight

2022-06-30 17:39 UTC, bhusang commented
The temperature limits for standard FR4 are -50 to +135. I increased the tag-connect footprints to those new limits. This issue is interesting because if you used a different substrate, the limits would be different so we need some way to capture the substrate Tg.

2022-07-08 18:16 UTC, electricfungi approved these changes

2022-07-08 18:17 UTC, merged