Dev to main
JITx-Inc/open-components-database pull request #444
Opened 2023-08-31 23:36 UTC by erwin-lau

APPROVED-DISTRIBUTOR-LIST in `defenum` goes to `main` from `dev`.
This is supported by `2.16.1` published.

2023-08-31 23:38 UTC, bhusang commented
Are you sure you want to merge to main versus dev? I thought that the dev -> main was automatic during the jitx-client release flow if ocdb was updated...

2023-08-31 23:42 UTC, erwin-lau commented
> Are you sure you want to merge to main versus dev? I thought that the dev -> main was automatic during the jitx-client release flow if ocdb was updated...

Good question. I am using the `dev` commit SHA in jitx-client in PR https://github.com/JITx-Inc/jitx-client/pull/3031
Is it sufficient, @jwatson0 ?

2023-09-01 14:25 UTC, jwatson0 requested changes
Change to ocdb `dev` branch

2023-09-01 14:32 UTC, S2000Erwin commented
In this case, it is not needed. The whole purpose of this PR is to merge the tip of dev to main.

2023-09-01 16:27 UTC, closed without merging